[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "KlippyRPCShim"
version = "0.0.1"
description = "Client for Klipper's Unix socket API RPC interface"
requires-python = ">=3.0"
